### ISSUE TITLE
It can't work in v1.7.2

### ISSUE THREAD

**Issue by zhangbg** [alysov/fold-lines#3]
It can't work in v1.7.2, how to fix this bug?

**Comment by alysov** [comment]
I am not experiencing this.  Could you post the details of your setup/plugins being used?  Perhaps there's some interference between them?

**Comment by matheo** [comment]
I've just installed this plugin on 1.8.0 and it worked nicely.
Had to move the mouse next to the line numbers to realise it was there hehe
Thanks a lot for this!

**Comment by alysov** [comment]
@matheo Thank you so much for the kind words!  If you have any suggestions on how to make it better, I'm definitely open to them.

**Comment by alysov** [comment]
Closing this issue since the plugin works in the latest version of Atom, 1.9.4
