### ISSUE TITLE
Deprecated selector in `fold-lines/styles/fold-lines.less`

### ISSUE THREAD

**Issue by vforge** [alysov/fold-lines#6]
In `fold-lines/styles/fold-lines.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .folded` => `atom-text-editor.editor .folded`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by gingerbeardman** [comment]
Done in pull #7

**Comment by alysov** [comment]
Resolved in #7 and published in v0.2.2.
Thank you everyone for all the help!
